# Generated by Django 3.0.3 on 2020-06-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractOpportunities',
            fields=[
                ('title', models.TextField(blank=True, help_text='title of notification', null=True, verbose_name='Notification')),
                ('noticeId', models.TextField(help_text='ID to identify unique notifications', primary_key=True, serialize=False)),
                ('department', models.TextField(blank=True, help_text='name of publishing agency or department', null=True, verbose_name='Department')),
                ('subTier', models.TextField(blank=True, help_text='name of publishing department sub-tier', null=True, verbose_name='Sub-Tier')),
                ('postedDate', models.DateField(verbose_name='Posted Date')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Deadline')),
                ('link', models.URLField(help_text='link to detailed website', verbose_name='Details')),
            ],
        ),
    ]
